---
- name: Agent-imgod | Install imgod
  become: true
  ansible.builtin.apt:
    name: irp-im-god
    state: '{{ irp_install_state }}'
    update_cache: true
    cache_valid_time: '{{ apt_cache_valid_time }}'
  notify:
    - Restart imgod
  tags:
    - irp_update

- name: Agent-imgod | Create systemd target
  become: true
  ansible.builtin.template:
    src: imgod.target
    dest: /etc/systemd/system/imgod.target
    mode: 0644

- name: Agent-imgod | Create systemd services for each instance
  become: true
  ansible.builtin.template:
    src: imgod.service.j2
    dest: /etc/systemd/system/{{ item.service_name }}.service
    mode: 0644
  loop: '{{ imgod }}'
  loop_control:
    label: '{{ item.name }}'
  notify:
    - Restart imgod

- name: Agent-imgod | Enable and start each service
  become: true
  ansible.builtin.systemd:
    name: '{{ item.service_name }}.service'
    enabled: true
    daemon_reload: true
    state: started
  loop: '{{ imgod }}'
  loop_control:
    label: '{{ item.name }}'

- name: Agent-imgod | Enable and start target
  become: true
  ansible.builtin.systemd:
    name: imgod.target
    state: started
    enabled: true
    daemon_reload: true
