---
- name: Get inventory for BGP push agents from app
  hosts: all
  gather_facts: false
  run_once: true
  tasks:
    - name: Fetch inventory
      delegate_to: localhost
      serverscom.irp.get_agents_inventory:
        inventory_type: BGP_PUSH
        irp_api_host: "{{ irp_api_host }}"
        irp_api_user: "{{ irp_api_user }}"
        irp_api_password: "{{ irp_api_password }}"
        ssl_verify: false
      register: bgp_push_inventory_request
    - name: Save BGP push inventory on controller
      delegate_to: localhost
      ansible.builtin.copy:
        content: '{{ bgp_push_inventory_request.inventory }}'
        dest: 'inventories/inventory-agents-bgp-push-{{ tier }}.yaml'
        mode: 0644
