---
- hosts: all
  gather_facts: false
  become: true
  tasks:
  - name: Find Grafana container ID
    ansible.builtin.command: docker ps -qf "name=scmon_grafana"
    register: grafana_container_id
    changed_when: false

  - name: Reset Grafana user password
    community.docker.docker_container_exec:
      container: "{{ grafana_container_id.stdout }}"
      command: "grafana-cli admin reset-admin-password {{ new_password }}"
    register: pwd_reset_output

  - name: Print the last line of reset output
    ansible.builtin.debug:
      msg: "{{ pwd_reset_output.stdout_lines[-1] }}"
