---
- name: Reinstall staging
  hosts: all,!postgres
  gather_facts: false
  tasks:
    - name: Check if Ubuntu image is specified
      ansible.builtin.assert:
        that:
          - os_image is defined
        fail_msg: No image specified

    - name: Reinstall OpenStack VMs
      delegate_to: localhost
      ansible.builtin.command: openstack server rebuild {{ os_vmid }} --image {{ os_image }}
      environment:
        OS_AUTH_URL: '{{ os_auth_url }}'
        OS_PROJECT_ID: '{{ os_project_id }}'
        OS_PROJECT_NAME: '{{ os_project_name }}'
        OS_REGION_NAME: '{{ os_region_name }}'
        OS_IDENTITY_API_VERSION: '{{ os_identity_api_version }}'
      changed_when: true

      when: os_vmid is defined

    - name: Wait for servers to come up
      ansible.builtin.wait_for_connection:
        delay: 30
        timeout: 300
