---
clickhouse_http_port: 8123
common_monitoring_clickhouse: true

generic_apt_repos:
  - name: irp-clickhouse
    key_data: |
      -----BEGIN PGP PUBLIC KEY BLOCK-----

      mQINBGDLFAcBEADItn8bhw4LwggeDScJceHrDoikgSkOQyHojMCfwmSBxdB6CUyG
      Po+bj/ox9gCI0pvvjSspJhykTJjkXMI/ZcCkkkg/HW2rYTrbgnScBM4ckEg+ywLS
      2u7CIZ4x5dp6glqH97HXkDZWhZY/ASeOvV18FUgTJM4H7ZO+SbfRZF9tUW9so0QX
      G7mk3TXsL0CWe69l6ZLSuB+X8W+asmbPz9ZKxICdfC8vTUSk6dV2yJADlca11t/v
      mEJXtHpu1S1b5h6/AnNeytnj8uoFzqaQ+gbQ0g3Gu5sWKVvHFMCS+SzqvGKYUOlW
      ZEK90dW3Xq/z2NFPu+HklZxoJnsC3KpgvUjayxwDf1mrvip2Wl83/Nuv4DhigeNn
      D9BU0EYbceUP4REG2COc0djjfY9h0elWneTjyO3Wom21Bmp7zCyfJLU4LVcyetnB
      CtdOmOUALEQAURxUwYpPj1ZpKWdyc63QC6A06csmp10yVrpH3Jcc+i+zxxkPr3OE
      6n3iB/hzylUudAR94Bb0cbXJW69XsQybfNeG4BiRtpN+cdai44Bbn6/Ed3JOKzLv
      8tOW/xHbFaQGeHWBgKZdVm/LU9JEFWB7lGgBtjcDobJnkPmiUK6WSDQh4r/hyD8U
      AFXh+FJyoNDTRYI3rm3aQAdOrJpKoCCn4VALniAqUp8CsASDdsiyOsaG/wARAQAB
      tBVEZXByZXBvIGFwdGx5IEdQRyBLZXmJAjgEEwEIACIFAmDLFAcCGy8GCwkIBwMC
      BhUIAgkKCwQWAgMBAh4BAheAAAoJEDpHadtq6DTn7AwQAIYTMuSkSsJKtIniNxLn
      GLSHsT+eca46EEDOu3jbAAmgIpySNyeTKDmVR0nqIG/XQiPUgT253xbjQE2LwRF3
      QeqhkLIuU+Kqo+Khyo6cODg5OOqJ1Te9gKwPY/ydFtzeAeZeL0oJ3l5PluefAu2z
      9G1MOMrhjrYhYAKM6YxuDH0qW07EAzD2bNy1Iz/Yu/uGmIsdABhM8y9IcVfiHccK
      4gAN2dJMLVrNJdlSJ197PpySXZVkcfm2DOiqv2pnjcefcDTdegC93yMZCg/reC6O
      Yly0cNScgTwGne3Uy5pgKBseHbeZ2Bj5t5SSOODT2zc0Cno8npaOTM+fUkkQSQya
      aBzyGqQ9Y0qxScZeLlRI2k9XIFVji1pm2owLpqsT9lUdA9XZBs2Nd20vb24nxYHb
      WbUVWtSqT5ohFYmfYimsb4RXcsepxiI3IF7d+u/JiW1kpuMYO69Q9yzp8V59g4pL
      ReSnMO2e3dwpeZ/4xxqbr/IAs5N2ycAjqXXq11cJ54a7uTZXUCbFZQgPehu+Qhd7
      aphDvL1Jzzd/5xXv25vfUoMo7U0Za4PxQkQsIItTbQQeyt5QA/pzusvnr4c586Lt
      0//VroWazTBX1JI2mte+jI5NX4fdaa8A4z6x5vwdkBuNhXFib1aIFSG6XsEjSo+y
      tPXElGfO+wtg+TFKTLb1ASRpuQINBGDLFAcBEADLX04lnfE1kI7uMwtMfQciUyc8
      KGK892t+fS4fJIMtUn+HipHBatm2vnmnf0djUw7gusgY+qv4xKfi1Uc7TRS62zUu
      GybKMkMEnHb0bECUMQsyh7WutMOEod6/knqsUs3KjdaLI+ok2dC7HwRz7jl+xM42
      vA5dlWEvgM7tGm4h7NZsI5itZdTtZQ4xkXJhACky6UdLEC8noCgCjsFujusm/7SJ
      0IvZHvzDQp3DuIISz/KyZ5f/O/acQTUoSrvXDApY/Bg6MMqvUhEBQWCSgt34XuIV
      pQoJO2pgn8uIo3d6jsfumYSIMHbtICM6uEvtoovRXaVwG31zeUB20U6DeP6KcuRq
      a4OQedIeO1gpFD1r8Q8uHhDHN5DDiEe/+Ng4HTZFPVtMAizvUVADL1m8BG3rFYxt
      xQknYN3YES0rheOkua4TCw5DjX+HpOpsCJ/iFEF4R4TQnDqjY5xeQMuM39JXzo4z
      7eSIcjqtyed5qMZ2l2qtu7ipGI0Je3TCw1DClN5l6f4yXssW4b45PArGz5c3cN85
      f99pIhrJr25GqGVB17fgXwIOlj+eIU1o+4KTaLhkFHDW8DgIq3Ch9b9+eRqtWW5t
      lJ+ecgPsh9BQih4fR1S2QPoC1dVmxZzdJlaJzgtgFoKh+vE7fbStkkYZ0ee+APDW
      sOTI+JRDO/CZ7E742QARAQABiQQ9BBgBCAAJBQJgyxQHAhsuAikJEDpHadtq6DTn
      wV0gBBkBCAAGBQJgyxQHAAoJEPYgt+cMUeUrDc0P/3CPjtZH5NC9EZ/ThORhpDr7
      UM7aDTOkAHzalj5vwXTWx8SyJmZuKrhhB0ZKdhURRbCDATa68lgDNg248ekDtmoC
      KmMutDkxWLJLPraEyQ45LieMrnQ+4flQx5cOquTzLr78PeMD29hazt/lcBpdqBK8
      +85E7OakfYpFb/l7se+/5U2qyrWlj00BOuqaezJu3QvyUmFBgztuIcZh7OQqS1aq
      qTcZN/9dSQftG2j0EDXHkbEc9pSKw3F/8t9CwGXLToVXvg+zqxn0otZ1+qOBsuc5
      7CCj01hym4Lq06CajG4Uut9n9/IWWVScO2UWTf79Ch7rH7JQpim7vu0rQllpL5Fh
      E54nQU1owCkaDn+C9go+CnuA+zEyEFVjr+seQ6XHFgcpAOGyCwZoAf9O2zPAiASC
      KHxnp4dDZIs3GBwSk2oVusMeJC0CrifqhDhbx7oC0Jh5NITmnsUWQ2PqUHmi+GZh
      jVYM3cZW0fG+8h/bC3Npi5hjC/yC1ogg1X7GwwkrJGhfASzxnvGWcOy85qIhYwS/
      6IMdLWi1l4hoA3o7CA0RlBj6al3jggfmtFbk5xsBo1n1fG4VN72ab24JwCw/ZJX6
      AelWhnqDe1IDGeBxcpwRiN7Fq7rKvHzM1HOCnpSE6GIbQAFehADEmwyVnD46ViRZ
      gnl5xnlnTrC8NT7wZcXeLqYP91/pdFNtXAliIYLFHw+d0aZ1T1IQ+hS/RTQtU9jo
      k6EvPS7edcG1kAKGTPVGHnrsLI9qmCvQGdscjvxK5WCuk+DoPDg/AK+4z+nkUDQ2
      mzwB06H7pEBXM8dZNbZtGhJQoujjH1BTI7+FhjVmCAubKw6thk0QyhN+U7DQ2YwY
      MU8EdOowptUTC3RciynYBhCHVF45kb/134NfscuyLK8dcPAKN+3rZqLHdYSQ0ZSv
      8qwhEZWx3dL2H85b1n+srdR1wPvkIMN8l16PF/rQQC2Gl+t7FAb21KiIrmYIsR3z
      tGd+kOHoTdpm8NNGtdUpL19LKcwDqL/4aQ8Koi5bBSYai9e99u+mgoTRN8AvQOHq
      NLJGCWKUTiRte7MyA9/I1Fhdra3ORGIxVzlX6w+UBDuMImRUp8cXmT06NYh0NXwh
      mJOD0GputPgk3O76ORai0ISjH/4yNtVoECTvAjn5vxI153zVdJTjN7fKc/vEPRC4
      ivewZvdQkgN22f3UmJPFb+2sWP9DQ6Kp8Rf2wXhFlEdi6kjy2bIvWf81j3s7aATu
      AiDlMwZ4oW1XgYA/V2RWxH3BHkos7WGg+TihOoiVSuzQMiYjYzLUzZkwTBfvBUlB
      bFPNN49h2asdTrRIiVD/TJlXBsXuhs30Qq94LP0Zm0YXIZje4nsepCEIl2vqBXSf
      1jY=
      =DPSu
      -----END PGP PUBLIC KEY BLOCK-----
    repo: 'deb http://{{ irp_apt_repo_host }}/clickhouse lts main'

  - name: clickhouse-backup
    key_data: |
      -----BEGIN PGP PUBLIC KEY BLOCK-----

      mQINBGDngP8BEAC8fpW6Fy9p7SPpHJ03debhSKmzlo7rOjp/cDkYu+MVsWMEui5l
      RcPvg2D53AbZcehtGIk1QUZe14mIYJPrGQgtvN+xNs0/QLCWhaetR4MpWn0dqPPr
      gO+xrwmFIN9WDyu9Tnj0ahTyQ2xJmVfjDJJZx3njRwOQzv9ENllG9d9x0HB9Uqy5
      5VqJini/Xmp/bZiqi5iiE65O3Byrx8tvyeWAO45hyiv5BAeXXSviVwxSaRl75Z29
      dtZvatp4iik2oRyY7VZvYwi7AZ3FkL5abMQakB9PIyQYxBAlOSaJkF+b4VWxhnZH
      M8Rj1Xpw9Nl9twQLj+eddPlllo1Uy/ldV7RuxvuAd+JwouRj/NIaT/TK3JWhrUh1
      VjEl9dl8HTycMI5b5cnhSF5t4usrcVFdwRTR1AFpR0y3c6l/Hvdsfn0SCDhcDWUd
      WqTTgUQRshlN2arMu7NaxB4aBDYJQlkwAQsIrHuO4e6jaPEH1GHM09rL2RU1zHD6
      UyEu4jYTt2PD8Gp1gGxVBcnQGbOgZX4psShLOyYM91PIwqM7HNCT1wkAtZk5q2e/
      qn+5YfCncNdP975PHNTETJPKNb5kHXADOlr96Q3YJuhM03s5q4wgZNDmO+P4+QW/
      0zL8SH4nHWEgbgbYnD7elFJq3GuAh/WN+KYxyhaJBX06u/XQ4xYgj5v+4wARAQAB
      tBVEZXByZXBvIGFwdGx5IEdQRyBLZXmJAjgEEwEIACIFAmDngP8CGy8GCwkIBwMC
      BhUIAgkKCwQWAgMBAh4BAheAAAoJEDZhfLFYkWXbBfEP/0XnWCeim20/l++JX3H2
      RmHSlSE3jcjcjSHO7MchJfP7bRKhzq55i4U/dgOoh3Vn1yZUPoZhHsTGkzrBhmRT
      uXsodwSDP826WRg1Ff81yRbYf1S432aiJ8gPvr5ABOexx+X4e49lpgKCTetey3P7
      AVszlnXKgSeBWk86HioCuQaskLhKQmGvAtl/40ZDW5187V3QgFs2Y1vh4yjF3MVT
      sYvevgNS3Yazd3OZ00uQUCvYgexjrseNMHNXOOHAz8UKqDOcnaE0vpAF1oaRNVja
      mHjxvB5xpqA3ldHFXmrmUH00lT4pbEDoXT1bRTb2jDKxbHwalxocuuhsZUjzTJOe
      HrnGySCNJAp7R7g/vmdk2gR8dSScClZH4TwT7WNlII0o3gRcU3xztzk2M320pY+d
      DKLDD0WgSmvJ7GEyUWn1ok7lIRNurdMx70lEtsUMIC9Dl+R+nrruYg1gKBDRmL5b
      yg/Lx6HTFyhlgUKGvYZcI/DBoDSHIIAwwiq8tY4dhT0mDUzHf9OVsiJeYBLSgSmK
      QR9rN75kK4CCTLwqWAhETyJbgnetpOWAV6Ab1eVwaC9P9xWCoD+6V00sRF7EL6Lr
      xZuB6MuCOIUF4aYBJ9PEPAERwoPa7M/V0GUtrDv3h0S5eKvRDKvitaqqB1jOYu56
      jR42ADkEyV0j/i3xtadoiuYuuQINBGDngP8BEAC969OQNYIb+r/rmFviwU7quy79
      ibogvHtSym41TRifzBi5ONiegVN7AhnZYEBhhQeFpt1YS4ppu6R+PswRYGYUOcyq
      gf7fEX9JSUGIM/E1gyuBqe9TaoIL/fHG9zyeonoWKbmxEu0txowM1jvJQmX5b0dm
      AaHr7EpzR3DKtj8MNKDT8B6ZNEDyRrXJ10FoX3bk4NhSaSY/68IDejODSIFJaN0T
      KnycyYhwTdJhDTUDu2lNV4KUUd/wAiERTiKh0ySCTuQKZ3D8qfDIneh14yEnnYeW
      zasEA/DCYlll5PfZ5RdTXX12SN6Pj4SeIa0C8eMYdjKO/fAlGZglZNav0MCZDb1t
      gUu4v/hFSijUJW9DYoQhXS+mXBPVMFgUuputUkPkdaMURzT5DUkDMzJh1qcjEKyO
      xc2oVYUL4hQnrP8ZBNQpqBHyOqw1FwQpC4ASYQK4gvkLkz5NL7it228RlaDRQkwF
      rDI75+K6KgX3qrNWZiPOSLPEGimHT55nwK+FREXglsgab/CgFUtIM1Lldryv3JGk
      tF3+2aWFdhRRa0jo4XBcHLw90EptUPDAh7sYAMoB1qNuaZTtxRdMPiM9nL5UeN97
      BUOwM/nYw13vGx1bYrGG7UswUsMpkob+bTsdUJsDbYmV3FMsBtEmDgfugUfOFSy8
      /Idsrp8I0ePZF4d2DwARAQABiQQ+BBgBCAAJBQJg54D/AhsuAikJEDZhfLFYkWXb
      wV0gBBkBCAAGBQJg54D/AAoJEPGHSNn7VkPU9xkP/ixp6Md+QvSONhoVM4pMEuRs
      nvgWwnSdhDIWA1aoKEUeG7M6tnYf1dMZ1z4MN1Unucn/E34n9QLvMGknTZg2gdt7
      /cYjLHm4MnwEDpioHE4vUYkLv4onVp7xQVj2zBMvtyr4oJ7zZO3kqgdo69cDR2dB
      yc0odD6cNWt6tGkJwz6AIaZtp1W4QDy1RHOgic6qAHGs+ONv5gAl+g3wOY89485z
      nC7EzZj6druXmo5zm4Ib2OA6TbSE8Laz60D4CyGoTyyrCyY0la9nu+mZyOd0PXvy
      sLiihZZaUqujNFQaNKqCf6thzvts5JtqKo3idScQSupkW0f5CzJemdcle7xvUz6s
      ijgb+s38sonWQ1ilsJzrZigKM6hquR7DPSFa4FhgfMr4acqQx34wJte6IrrjV3c8
      VRLd6vsVQP2uZMKHOqoDo1aaswj0ArVKPb+YX22481deNoaD877453Yv+OCvum93
      JY61Ohdpa+SliIjtyQeuljuTazt+C2Q/QYUPmXa8fvvW77Syt+lddTmK1rQ7L3lt
      MbmleYYUhP7hzs/D+SHA/CuD5mmMaBTZlmGYW0V5PE6mqQ5tSGEj+P1aNMsyAta5
      JhDinmZHoGsTh+0QEwtMs9omAWpxb4pdKwIN/HIf/q300/iVTstHbVZnTrk9dbrN
      BpiVVGZi/QUDJUwlG2kDKG0P/0jRkDMUZDJXq0lLy2gGRpZNPC7eyObo3f6bLDyx
      lsFMny69txvqDMHF08UjlEF2ZBIcqpVWRw9K8u+yDKX1Qy0xVO/nVme5uB93gbDo
      JJwJgaoyGtsR3AG/0WWz6tZxf3QQinBMXIKVHeipGOx+MMXrkgfEqskpY/D9+IjQ
      j8zPLxLPQ4l6HJknuCoxceeGiSnKatJR475n3qW6Jg9yLRWz9Vsc69EHGlPPMqgF
      R5J9WPeKT8tfmEvFUcgvhkt+g4ekT9jcEJY1j1Dk0MdG5ciS8MwKOOCImaEaB1tO
      auTX/OPbcNQIrOoT9knLNRhIP++4Cdb3EgvJi6EIZmEgzrPVxNzOKjGRsDnDQsD6
      DyO5kGwiTbgTW7S7UO/JuFLBZ+sRSmzV0m+JCVzq+/83aH4Yg5EFGRRIBNb3E+7J
      k8KPVwq31AhpYp56jgU/GgjFz04T4D4oGdcx7jpyQuU1OFO5OBGQC8tkc3B+Z2j8
      UGKrCR+0QnJcKYhjdsi71mytsJGwap8IsIrVZThY4/BADcValbs8G1cyUP+rGX4s
      L7rgEiDICs+4qjh06hJ3Dxr7dhJyxzoFvlaIyuBMkBIka6+PasuIky6bI8Se59io
      SJ6ac5Husj+Nuq7oC+ghPJDKfp0Wdpbg4qdmxhUqFy3skVKSS+tuU/w2KNNPWcPH
      GGvV
      =dNqf
      -----END PGP PUBLIC KEY BLOCK-----
    repo: 'deb http://mirror.servers.com/.deb/repo1/clickhouse-backup focal main'

clickhouse_backup_config:
  click6.irp.servers.im:
    clickhouse_backup_access_key: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          64623432333163306264313637333637306332663136343265616332653737376530646563653862
          3135393234326130653666326439346265343136643933350a646234643035333136653466333136
          65323434326562663561353465303033313431613538633232313031376633633864323637326637
          6539323333346564350a363462626636613131626161333939653161363761323239383166396436
          65373066656230333133663364336230616639353766636361363539316263663934616539356532
          6466633839363463366430623033343066616439343635313830
    clickhouse_backup_secret_key: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          33656630373435373132633732653236356531306635306633303331336636666362373132333564
          3839333035656133343764373062616633333765343537310a623765393034656533353636623730
          32303665346262666136323663633631643330393065343134326538346466356663643835313834
          3061386131663265640a303635643834363738626431613537313466356430386564343562313439
          66613839316462393233393133383137336337313765383535626366653637663534626665356338
          3932363061353566343332326139386338313439396439653938
    clickhouse_backup_bucket: irp-archive-db-backups
    clickhouse_backup_endpoint: https://storage.files.nl01.cloud.servers.com
    clickhouse_backup_check_table: archive.snmp_location
