---
- name: Install haproxy
  become: true
  ansible.builtin.apt:
    name: haproxy
    state: present

- name: Configure haproxy
  become: true
  ansible.builtin.template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    mode: 0644
  notify: Restart haproxy

- name: Start and enable haproxy
  become: true
  ansible.builtin.systemd:
    name: haproxy
    state: started
    enabled: true
