---
- name: Install frr
  become: true
  ansible.builtin.apt:
    name: frr
    state: present

- name: Configure bgp
  become: true
  ansible.builtin.copy:
    content: |
      router bgp {{ bgp_asn }}
       bgp router-id {{ bgp_router_id }}
      {% for peer in bgp_peers %}
       neighbor {{ peer.ip }} remote-as {{ peer.asn }}
      {% endfor %}
    dest: /etc/frr/bgpd.conf
    mode: 0640
    owner: frr
    group: frr
  notify: Restart frr

- name: Start and enable frr
  become: true
  ansible.builtin.systemd:
    name: frr
    state: started
    enabled: true
