---
production:
  hosts:
    click5.irp.servers.im:
      ansible_host: 10.215.2.254
      ipv4_additional_addresses:
        - 188.42.219.235
      public_ip: 188.42.219.235
      common_monitoring_dell_hw: false
      common_monitoring_interface_public_redundant: false
      common_monitoring_interface_private_redundant: false
    click6.irp.servers.im:
      ansible_host: 10.215.2.245
      ipv4_additional_addresses:
        - 188.42.219.229
      public_ip: 188.42.219.229
      common_monitoring_dell_hw: false
      common_monitoring_interface_public_redundant: false
      common_monitoring_interface_private_redundant: false
    click7.irp.servers.im:
      ansible_host: 10.215.3.91
      ipv4_additional_addresses:
        - 142.91.155.157
      public_ip: 142.91.155.157
      common_monitoring_dell_hw: false
      common_monitoring_interface_public_redundant: false
      common_monitoring_interface_private_redundant: false
    click8.irp.servers.im:
      ansible_host: 10.215.2.182
      ipv4_additional_addresses:
        - 142.91.9.134
      public_ip: 142.91.9.134
      common_monitoring_dell_hw: false
      common_monitoring_interface_public_redundant: false
      common_monitoring_interface_private_redundant: false

clickhouse:
  hosts:
    click5.irp.servers.im:
    click6.irp.servers.im:
    click7.irp.servers.im:
    click8.irp.servers.im:

clickhouse_backup:
  hosts:
    click6.irp.servers.im:

all:
  vars:
    test_var_for_override: defined_in_inventory_file
