---
- name: Create systemd service
  become: true
  ansible.builtin.template:
    src: systemd_exporter.service.j2
    dest: /etc/systemd/system/systemd_exporter.service
    mode: 0644
  notify: Restart systemd_exporter

- name: Pull systemd_exporter docker image
  become: true
  community.docker.docker_image:
    name: '{{ systemd_exporter_image }}'
    source: pull
    state: present

- name: Enable systemd_exporter service
  become: true
  ansible.builtin.systemd:
    name: systemd_exporter
    state: started
    enabled: true
    daemon_reload: true

- name: Create prometheus target
  become: true
  ansible.builtin.copy:
    dest: /etc/scmon/prometheus/file_sd.systemd_exporter_{{ inventory_hostname }}.yaml
    content: |
      # Ansible managed
      -   labels:
              __metrics_path__: /metrics
              job: systemd_exporter
              scmon_name: {{ inventory_hostname }}
          targets:
          - {{ systemd_exporter_listen_address }}:{{ systemd_exporter_listen_port }}
    mode: 0644
